<?php
/* Functions document
	- Thumbnail sizes
	- Sidebar widgets
	- Custom fonts
*/

// LOAD BONES CORE (if you remove this, the theme will break)
require_once( 'library/bones.php' );

// USE THIS TEMPLATE TO CREATE CUSTOM POST TYPES EASILY
require_once( 'library/custom-post-type.php' );

// CUSTOMIZE THE WORDPRESS ADMIN (off by default)
require_once( 'library/admin.php' );

// LOAD ADVANCED CUSTOM FIELDS PLUGIN
define( 'ACF_LITE', true ); // hide the ACF menu item in the left sidebar of the Admin Area
include_once('library/advanced-custom-fields/acf.php'); // load ACF from the theme's library folder

/*********************
LAUNCH BONES
Let's get everything up and running.
*********************/

function bones_ahoy() {

	// let's get language support going, if you need it
	// load_theme_textdomain( 'bonestheme', get_template_directory() . '/library/translation' );

	// launching operation cleanup
	add_action( 'init', 'bones_head_cleanup' );
	// A better title
	add_filter( 'wp_title', 'rw_title', 10, 3 );
	// remove WP version from RSS
	add_filter( 'the_generator', 'bones_rss_version' );
	// remove pesky injected css for recent comments widget
	add_filter( 'wp_head', 'bones_remove_wp_widget_recent_comments_style', 1 );
	// clean up comment styles in the head
	add_action( 'wp_head', 'bones_remove_recent_comments_style', 1 );
	// clean up gallery output in wp
	add_filter( 'gallery_style', 'bones_gallery_style' );

	// enqueue base scripts and styles
	add_action( 'wp_enqueue_scripts', 'bones_scripts_and_styles', 999 );
	// ie conditional wrapper

	// launching this stuff after theme setup
	bones_theme_support();

	// adding sidebars to Wordpress (these are created in functions.php)
	add_action( 'widgets_init', 'bones_register_sidebars' );

	// cleaning up random code around images
	add_filter( 'the_content', 'bones_filter_ptags_on_images' );
	// cleaning up excerpt
	add_filter( 'excerpt_more', 'bones_excerpt_more' );

} /* end bones ahoy */

// let's get this party started
add_action( 'after_setup_theme', 'bones_ahoy' );


/************* OEMBED SIZE OPTIONS *************/

if ( ! isset( $content_width ) ) {
	$content_width = 640;
}


/************* THUMBNAIL SIZE OPTIONS *************/

// Thumbnail sizes
add_image_size( 'atra-700', 732, 360, true );
add_image_size( 'atra-300', 300, 225, true );

/*
to add more sizes, simply copy a line from above
and change the dimensions & name. As long as you
upload a "featured image" as large as the biggest
set width or height, all the other sizes will be
auto-cropped.

To call a different size, simply change the text
inside the thumbnail function.

For example, to call the 300 x 300 sized image,
we would use the function:
<?php the_post_thumbnail( 'bones-thumb-300' ); ?>
for the 600 x 100 image:
<?php the_post_thumbnail( 'bones-thumb-600' ); ?>

You can change the names and dimensions to whatever
you like. Enjoy!
*/

add_filter( 'image_size_names_choose', 'bones_custom_image_sizes' );

function bones_custom_image_sizes( $sizes ) {
	return array_merge( $sizes, array(
		'atra-700' => __('732px by 360px'),
		'atra-300' => __('300px by 225px'),
	) );
}

/*
The function above adds the ability to use the dropdown menu to select
the new images sizes you have just created from within the media manager
when you add media to your content blocks. If you add more image sizes,
duplicate one of the lines in the array and name it according to your
new image size.
*/


/************* ACTIVE SIDEBARS ********************/

// Sidebars & Widgetizes Areas
function bones_register_sidebars() {

	// ***************************
	// Registering EVENTS - BANNER 
	// ***************************
	register_sidebar(array(
		'id' => 'banner-events',
		'name' => __( 'Events – Banner', 'bonestheme' ),
		'description' => __( 'Member banner ad space (728x90 px) on all Event pages.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));
	

	// ****************************
	// Registering EVENTS - SIDEBAR 
	// ****************************
	register_sidebar(array(
		'id' => 'sidebar-events',
		'name' => __( 'Events – Sidebar', 'bonestheme' ),
		'description' => __( 'The sidebar area on all Event pages. Ad space (336x280 px)', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// *******************************
	// Registering TRAIL NEWS - BANNER 
	// *******************************
	register_sidebar(array(
		'id' => 'banner-news',
		'name' => __( 'Trail News – Banner', 'bonestheme' ),
		'description' => __( 'Member banner ad space (728x90 px) on all Trail News (blog) pages.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));


	// ********************************
	// Registering TRAIL NEWS - SIDEBAR 
	// ********************************
	register_sidebar(array(
		'id' => 'sidebar-news',
		'name' => __( 'Trail News – Sidebar', 'bonestheme' ),
		'description' => __( 'The sidebar area on all Trial News (blog) pages. Ad space (336x280 px)', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// *******************************
	// Registering RESOURCES - SIDEBAR 
	// *******************************
	register_sidebar(array(
		'id' => 'banner-resources',
		'name' => __( 'Resources – Banner', 'bonestheme' ),
		'description' => __( 'Member banner ad space (728x90 px) on all Resource pages.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// *******************************
	// Registering RESOURCES - SIDEBAR 
	// *******************************
	register_sidebar(array(
		'id' => 'sidebar-resources',
		'name' => __( 'Resources – Sidebar', 'bonestheme' ),
		'description' => __( 'The sidebar area on all Resource pages. Ad space (336x280 px)', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// ***************************************
	// Registering BECOMING A MEMBER - SIDEBAR 
	// ***************************************
	register_sidebar(array(
		'id' => 'sidebar-members',
		'name' => __( 'Become a Member', 'bonestheme' ),
		'description' => __( 'The sidebar about becoming an ATRA member.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// **********************************
	// Registering SOCIAL MEDIA - SIDEBAR 
	// **********************************
	register_sidebar(array(
		'id' => 'sidebar-socials',
		'name' => __( 'Social Media', 'bonestheme' ),
		'description' => __( 'The sidebar area on for Social Media.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// ***************************************
	// Registering MARKETING - SIDEBAR 
	// ***************************************
	register_sidebar(array(
		'id' => 'sidebar-marketing',
		'name' => __( 'Social Marketing', 'bonestheme' ),
		'description' => __( 'The sidebar area on for Marketing.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));

	// ***************************************
	// Registering CONTACT US - SIDEBAR 
	// ***************************************
	register_sidebar(array(
		'id' => 'sidebar-contact',
		'name' => __( 'Contact Us', 'bonestheme' ),
		'description' => __( 'The sidebar area on for Contact Us.', 'bonestheme' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget' => '</div>',
		'before_title' => '<h4 class="widgettitle">',
		'after_title' => '</h4>',
	));
	
} // don't remove this bracket!


// ***************************************
// Registering CUSTOM FIELDS 
// ***************************************
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_board-members',
		'title' => 'Board Members',
		'fields' => array (
			array (
				'key' => 'field_539e3bea925ae',
				'label' => 'Board Title',
				'name' => 'board_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Vice President',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3cb1925af',
				'label' => 'Facebook Profile',
				'name' => 'facebook_profile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://facebook.com/name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3d04925b0',
				'label' => 'Twitter Profile',
				'name' => 'twitter_profile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://twitter.com/#!/name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3d90925b1',
				'label' => 'Google Plus Profile',
				'name' => 'google_plus_profile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://plus.google.com/+name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3e94925b2',
				'label' => 'Instagram Profile',
				'name' => 'instagram_profile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://instagram.com/name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3ef2925b3',
				'label' => 'Email Address',
				'name' => 'email_address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'name@email.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e3f22925b4',
				'label' => 'Member Description',
				'name' => 'member_description',
				'type' => 'textarea',
				'instructions' => '140 Character Limit',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'boardmember',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_board-minutes',
		'title' => 'Board Minutes',
		'fields' => array (
			array (
				'key' => 'field_539e437f25353',
				'label' => 'Meeting Minute PDF Links',
				'name' => 'meeting_minute_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '111',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_membership',
		'title' => 'Membership',
		'fields' => array (
			array (
				'key' => 'field_53e2381f7d459',
				'label' => 'Membership Description',
				'name' => 'membership_description',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e44a0478da',
				'label' => 'All-terrain Members',
				'name' => 'members_all-terrain',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53a382b73f401',
				'label' => 'Steep & Rocky Members',
				'name' => 'members_steep-rocky',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53a382dc3f402',
				'label' => 'Single-track Members',
				'name' => 'members_single-track',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e44e4478dc',
				'label' => 'Race Members',
				'name' => 'members_race',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e44cf478db',
				'label' => 'Club Members',
				'name' => 'members_club',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '114',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'slug',
				5 => 'author',
				6 => 'format',
				7 => 'featured_image',
				8 => 'categories',
				9 => 'tags',
				10 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_partner-information',
		'title' => 'Partner Information',
		'fields' => array (
			array (
				'key' => 'field_539e356e59674',
				'label' => 'Partner Website',
				'name' => 'partner_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e35b459675',
				'label' => 'Partner Description',
				'name' => 'partner_description',
				'type' => 'textarea',
				'instructions' => '222 Character Limit',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'partner',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_race-director-information',
		'title' => 'Race Director Information',
		'fields' => array (
			array (
				'key' => 'field_539ca49c5aab1',
				'label' => 'First Name',
				'name' => 'rd_first_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Johnny',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539ca50f5aab2',
				'label' => 'Last Name',
				'name' => 'rd_last_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Appleseed',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539ca5355aab3',
				'label' => 'Email',
				'name' => 'rd_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => 'name@email.com',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_539ca56e5aab4',
				'label' => 'Phone',
				'name' => 'rd_phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(123) 456-7890',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 20,
			),
			array (
				'key' => 'field_539ca5cf5aab5',
				'label' => 'Company',
				'name' => 'rd_company',
				'type' => 'text',
				'instructions' => 'Organization or Management Company',
				'default_value' => '',
				'placeholder' => 'Running Organization',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_resources',
		'title' => 'Resources',
		'fields' => array (
			array (
				'key' => 'field_539e39732fe7b',
				'label' => 'Beginning Running',
				'name' => 'get_started_running',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e39aa2fe7c',
				'label' => 'Trail Maintenance',
				'name' => 'trail_maintenance',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e39c62fe7d',
				'label' => 'Running Organization-Club Links',
				'name' => 'organization_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3a362fe7e',
				'label' => 'MUT Article Links',
				'name' => 'mut_articles',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3a562fe7f',
				'label' => 'Book Links',
				'name' => 'book_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3a632fe80',
				'label' => 'Magazines Links',
				'name' => 'magazines_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3a8c2fe81',
				'label' => 'Ultrarunning Links',
				'name' => 'ultrarunning_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3afd2fe82',
				'label' => 'Running Camp Links',
				'name' => 'camp_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539e3b0a2fe83',
				'label' => 'Trail Running Blog Links',
				'name' => 'running_blog_links',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '101',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-information',
		'title' => 'Event Information',
		'fields' => array (
			array (
				'key' => 'field_539cb226ab8e8',
				'label' => 'Event Date',
				'name' => 'event_date',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '12/03/2014',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539cb245ab8e9',
				'label' => 'Start Time',
				'name' => 'start_time',
				'type' => 'select',
				'instructions' => 'Start time of earliest race, if multiple.',
				'required' => 1,
				'choices' => array (
					'12:00 am' => '12:00 am',
					'12:15 am' => '12:15 am',
					'12:30 am' => '12:30 am',
					'12:45 am' => '12:45 am',
					'1:00 am' => '1:00 am',
					'1:15 am' => '1:15 am',
					'1:30 am' => '1:30 am',
					'1:45 am' => '1:45 am',
					'2:00 am' => '2:00 am',
					'2:15 am' => '2:15 am',
					'2:30 am' => '2:30 am',
					'2:45 am' => '2:45 am',
					'3:00 am' => '3:00 am',
					'3:15 am' => '3:15 am',
					'3:30 am' => '3:30 am',
					'3:45 am' => '3:45 am',
					'4:00 am' => '4:00 am',
					'4:15 am' => '4:15 am',
					'4:30 am' => '4:30 am',
					'4:45 am' => '4:45 am',
					'5:00 am' => '5:00 am',
					'5:15 am' => '5:15 am',
					'5:30 am' => '5:30 am',
					'5:45 am' => '5:45 am',
					'6:00 am' => '6:00 am',
					'6:15 am' => '6:15 am',
					'6:30 am' => '6:30 am',
					'6:45 am' => '6:45 am',
					'7:00 am' => '7:00 am',
					'7:15 am' => '7:15 am',
					'7:30 am' => '7:30 am',
					'7:45 am' => '7:45 am',
					'8:00 am' => '8:00 am',
					'8:15 am' => '8:15 am',
					'8:30 am' => '8:30 am',
					'8:45 am' => '8:45 am',
					'9:00 am' => '9:00 am',
					'9:15 am' => '9:15 am',
					'9:30 am' => '9:30 am',
					'9:45 am' => '9:45 am',
					'10:00 am' => '10:00 am',
					'10:15 am' => '10:15 am',
					'10:30 am' => '10:30 am',
					'10:45 am' => '10:45 am',
					'11:00 am' => '11:00 am',
					'11:15 am' => '11:15 am',
					'11:30 am' => '11:30 am',
					'11:45 am' => '11:45 am',
					'12:00 pm' => '12:00 pm',
					'12:15 pm' => '12:15 pm',
					'12:30 pm' => '12:30 pm',
					'12:45 pm' => '12:45 pm',
					'1:00 pm' => '1:00 pm',
					'1:15 pm' => '1:15 pm',
					'1:30 pm' => '1:30 pm',
					'1:45 pm' => '1:45 pm',
					'2:00 pm' => '2:00 pm',
					'2:15 pm' => '2:15 pm',
					'2:30 pm' => '2:30 pm',
					'2:45 pm' => '2:45 pm',
					'3:00 pm' => '3:00 pm',
					'3:15 pm' => '3:15 pm',
					'3:30 pm' => '3:30 pm',
					'3:45 pm' => '3:45 pm',
					'4:00 pm' => '4:00 pm',
					'4:15 pm' => '4:15 pm',
					'4:30 pm' => '4:30 pm',
					'4:45 pm' => '4:45 pm',
					'5:00 pm' => '5:00 pm',
					'5:15 pm' => '5:15 pm',
					'5:30 pm' => '5:30 pm',
					'5:45 pm' => '5:45 pm',
					'6:00 pm' => '6:00 pm',
					'6:15 pm' => '6:15 pm',
					'6:30 pm' => '6:30 pm',
					'6:45 pm' => '6:45 pm',
					'7:00 pm' => '7:00 pm',
					'7:15 pm' => '7:15 pm',
					'7:30 pm' => '7:30 pm',
					'7:45 pm' => '7:45 pm',
					'8:00 pm' => '8:00 pm',
					'8:15 pm' => '8:15 pm',
					'8:30 pm' => '8:30 pm',
					'8:45 pm' => '8:45 pm',
					'9:00 pm' => '9:00 pm',
					'9:15 pm' => '9:15 pm',
					'9:30 pm' => '9:30 pm',
					'9:45 pm' => '9:45 pm',
					'10:00 pm' => '10:00 pm',
					'10:15 pm' => '10:15 pm',
					'10:30 pm' => '10:30 pm',
					'10:45 pm' => '10:45 pm',
					'11:00 pm' => '11:00 pm',
					'11:15 pm' => '11:15 pm',
					'11:30 pm' => '11:30 pm',
					'11:45 pm' => '11:45 pm',
					'TBD' => 'TBD',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539caf19ab8df',
				'label' => 'Event Website',
				'name' => 'event_website',
				'type' => 'text',
				'instructions' => 'Include http:// at the start of the URL.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'http://website.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539caf3cab8e0',
				'label' => 'Event Description',
				'name' => 'event_description',
				'type' => 'textarea',
				'instructions' => 'Additional event information and course details.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539caf5eab8e1',
				'label' => 'Event Street',
				'name' => 'event_street',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '123 Main St.',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539caf75ab8e2',
				'label' => 'Event City',
				'name' => 'event_city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Metropolis',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539cafd4ab8e4',
				'label' => 'Event Zip Code',
				'name' => 'event_zip',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 12345,
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 5,
			),
			array (
				'key' => 'field_539caff7ab8e5',
				'label' => 'Event Country',
				'name' => 'event_country',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'USA' => 'United States of America',
					'Afghanistan' => 'Afghanistan',
					'Albania' => 'Albania',
					'Algeria' => 'Algeria',
					'Andorra' => 'Andorra',
					'Angola' => 'Angola',
					'Antarctica' => 'Antarctica',
					'Antigua and Barbuda' => 'Antigua and Barbuda',
					'Argentina' => 'Argentina',
					'Armenia' => 'Armenia',
					'Aruba' => 'Aruba',
					'Australia' => 'Australia',
					'Austria' => 'Austria',
					'Azerbaijan' => 'Azerbaijan',
					'Bahamas' => 'Bahamas',
					'Bahrain' => 'Bahrain',
					'Bangladesh' => 'Bangladesh',
					'Barbados' => 'Barbados',
					'Belarus' => 'Belarus',
					'Belgium' => 'Belgium',
					'Belize' => 'Belize',
					'Benin' => 'Benin',
					'Bermuda' => 'Bermuda',
					'Bhutan' => 'Bhutan',
					'Bolivia' => 'Bolivia',
					'Bosnia' => 'Bosnia',
					'Botswana' => 'Botswana',
					'Brazil' => 'Brazil',
					'Brunei' => 'Brunei',
					'Bulgaria' => 'Bulgaria',
					'Burkina Faso' => 'Burkina Faso',
					'Burundi' => 'Burundi',
					'Cambodia' => 'Cambodia',
					'Cameroon' => 'Cameroon',
					'Canada' => 'Canada',
					'Cape Verde' => 'Cape Verde',
					'Cayman Islands' => 'Cayman Islands',
					'Central African Republic' => 'Central African Republic',
					'Chad' => 'Chad',
					'Chile' => 'Chile',
					'China' => 'China',
					'Colombia' => 'Colombia',
					'Comoros' => 'Comoros',
					'Congo' => 'Congo',
					'Costa Rica' => 'Costa Rica',
					'Côte d\'Ivoire' => 'Côte d\'Ivoire',
					'Croatia' => 'Croatia',
					'Cuba' => 'Cuba',
					'Cyprus' => 'Cyprus',
					'Czech Republic' => 'Czech Republic',
					'Denmark' => 'Denmark',
					'Djibouti' => 'Djibouti',
					'Dominica' => 'Dominica',
					'Dominican Republic' => 'Dominican Republic',
					'East Timor' => 'East Timor',
					'Ecuador' => 'Ecuador',
					'Egypt' => 'Egypt',
					'El Salvador' => 'El Salvador',
					'Equatorial Guinea' => 'Equatorial Guinea',
					'Eritrea' => 'Eritrea',
					'Estonia' => 'Estonia',
					'Ethiopia' => 'Ethiopia',
					'Fiji' => 'Fiji',
					'Finland' => 'Finland',
					'France' => 'France',
					'Gabon' => 'Gabon',
					'Gambia' => 'Gambia',
					'Georgia' => 'Georgia',
					'Germany' => 'Germany',
					'Ghana' => 'Ghana',
					'Greece' => 'Greece',
					'Greenland' => 'Greenland',
					'Grenada' => 'Grenada',
					'Guam' => 'Guam',
					'Guatemala' => 'Guatemala',
					'Guinea' => 'Guinea',
					'Guinea-Bissau' => 'Guinea-Bissau',
					'Guyana' => 'Guyana',
					'Haiti' => 'Haiti',
					'Honduras' => 'Honduras',
					'Hong Kong' => 'Hong Kong',
					'Hungary' => 'Hungary',
					'Iceland' => 'Iceland',
					'India' => 'India',
					'Indonesia' => 'Indonesia',
					'Iran' => 'Iran',
					'Iraq' => 'Iraq',
					'Ireland' => 'Ireland',
					'Israel' => 'Israel',
					'Italy' => 'Italy',
					'Jamaica' => 'Jamaica',
					'Japan' => 'Japan',
					'Jordan' => 'Jordan',
					'Kazakhstan' => 'Kazakhstan',
					'Kenya' => 'Kenya',
					'Kiribati' => 'Kiribati',
					'North Korea' => 'North Korea',
					'South Korea' => 'South Korea',
					'Kosovo' => 'Kosovo',
					'Kuwait' => 'Kuwait',
					'Kyrgyzstan' => 'Kyrgyzstan',
					'Laos' => 'Laos',
					'Latvia' => 'Latvia',
					'Lebanon' => 'Lebanon',
					'Lesotho' => 'Lesotho',
					'Liberia' => 'Liberia',
					'Libya' => 'Libya',
					'Liechtenstein' => 'Liechtenstein',
					'Lithuania' => 'Lithuania',
					'Luxembourg' => 'Luxembourg',
					'Macedonia' => 'Macedonia',
					'Madagascar' => 'Madagascar',
					'Malawi' => 'Malawi',
					'Malaysia' => 'Malaysia',
					'Maldives' => 'Maldives',
					'Mali' => 'Mali',
					'Malta' => 'Malta',
					'Marshall Islands' => 'Marshall Islands',
					'Mauritania' => 'Mauritania',
					'Mauritius' => 'Mauritius',
					'Mexico' => 'Mexico',
					'Micronesia' => 'Micronesia',
					'Moldova' => 'Moldova',
					'Monaco' => 'Monaco',
					'Mongolia' => 'Mongolia',
					'Montenegro' => 'Montenegro',
					'Morocco' => 'Morocco',
					'Mozambique' => 'Mozambique',
					'Myanmar' => 'Myanmar',
					'Namibia' => 'Namibia',
					'Nauru' => 'Nauru',
					'Nepal' => 'Nepal',
					'Netherlands' => 'Netherlands',
					'New Zealand' => 'New Zealand',
					'Nicaragua' => 'Nicaragua',
					'Niger' => 'Niger',
					'Nigeria' => 'Nigeria',
					'Norway' => 'Norway',
					'Northern Mariana Islands' => 'Northern Mariana Islands',
					'Oman' => 'Oman',
					'Pakistan' => 'Pakistan',
					'Palau' => 'Palau',
					'Palestine' => 'Palestine',
					'Panama' => 'Panama',
					'Papua New Guinea' => 'Papua New Guinea',
					'Paraguay' => 'Paraguay',
					'Peru' => 'Peru',
					'Philippines' => 'Philippines',
					'Poland' => 'Poland',
					'Portugal' => 'Portugal',
					'Puerto Rico' => 'Puerto Rico',
					'Qatar' => 'Qatar',
					'Romania' => 'Romania',
					'Russia' => 'Russia',
					'Rwanda' => 'Rwanda',
					'Saint Kitts and Nevis' => 'Saint Kitts and Nevis',
					'Saint Lucia' => 'Saint Lucia',
					'Saint Vincent and the Grenadines' => 'Saint Vincent and the Grenadines',
					'Samoa' => 'Samoa',
					'San Marino' => 'San Marino',
					'Sao Tome and Principe' => 'Sao Tome and Principe',
					'Saudi Arabia' => 'Saudi Arabia',
					'Senegal' => 'Senegal',
					'Serbia and Montenegro' => 'Serbia and Montenegro',
					'Seychelles' => 'Seychelles',
					'Sierra Leone' => 'Sierra Leone',
					'Singapore' => 'Singapore',
					'Slovakia' => 'Slovakia',
					'Slovenia' => 'Slovenia',
					'Solomon Islands' => 'Solomon Islands',
					'Somalia' => 'Somalia',
					'South Africa' => 'South Africa',
					'Spain' => 'Spain',
					'Sri Lanka' => 'Sri Lanka',
					'Sudan' => 'Sudan',
					'Sudan, South' => 'Sudan, South',
					'Suriname' => 'Suriname',
					'Swaziland' => 'Swaziland',
					'Sweden' => 'Sweden',
					'Switzerland' => 'Switzerland',
					'Syria' => 'Syria',
					'Taiwan' => 'Taiwan',
					'Tajikistan' => 'Tajikistan',
					'Tanzania' => 'Tanzania',
					'Thailand' => 'Thailand',
					'Togo' => 'Togo',
					'Tonga' => 'Tonga',
					'Trinidad and Tobago' => 'Trinidad and Tobago',
					'Tunisia' => 'Tunisia',
					'Turkey' => 'Turkey',
					'Turkmenistan' => 'Turkmenistan',
					'Tuvalu' => 'Tuvalu',
					'Uganda' => 'Uganda',
					'Ukraine' => 'Ukraine',
					'United Arab Emirates' => 'United Arab Emirates',
					'United Kingdom' => 'United Kingdom',
					'Uruguay' => 'Uruguay',
					'Uzbekistan' => 'Uzbekistan',
					'Vanuatu' => 'Vanuatu',
					'Vatican City' => 'Vatican City',
					'Venezuela' => 'Venezuela',
					'Vietnam' => 'Vietnam',
					'Virgin Islands' => 'Virgin Islands',
					'Yemen' => 'Yemen',
					'Zambia' => 'Zambia',
					'Zimbabwe' => 'Zimbabwe',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539cb1caab8e6',
				'label' => 'Entry Fee',
				'name' => 'entry_fee',
				'type' => 'number',
				'instructions' => 'Lowest or Early Registration.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53c8a01711758',
				'label' => 'Entry Fee 2',
				'name' => 'entry_fee_2',
				'type' => 'number',
				'instructions' => 'Highest or Late Registration.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53f7e2d864e47',
				'label' => 'Prize Money',
				'name' => 'prize_money',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_539cb1e4ab8e7',
				'label' => 'Event Type',
				'name' => 'event_type',
				'type' => 'text',
				'instructions' => 'Enter all that apply (Trail, Mountain, Ultra, Hill Climb, Relay, Cross Country, Snowshoe, Burro Race, Clothing Optional, Ride & Tie, Running Camp, Obstacle/Mud, Adventure/Stage Race, Beach, Stair Climb)',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 60,
			),
			array (
				'key' => 'field_539cb3f6ab8ec',
				'label' => 'Other Distance 1',
				'name' => 'other_distance1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e269b4c177',
				'label' => 'Other Distance2',
				'name' => 'other_distance2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_additional-event-information',
		'title' => 'Additional Event Information',
		'fields' => array (
			array (
				'key' => 'field_539e292c5752c',
				'label' => 'Event Facebook Page',
				'name' => 'event_facebook_page',
				'type' => 'text',
				'instructions' => 'Include http:// at the beginning of the URL.',
				'default_value' => '',
				'placeholder' => 'http://facebook.com/event',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e29ee5752d',
				'label' => 'Event Twitter Feed',
				'name' => 'event_twitter_feed',
				'type' => 'text',
				'instructions' => 'Include http:// at the beginning of the URL.',
				'default_value' => '',
				'placeholder' => 'http://twitter.com/event',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2a755752e',
				'label' => 'The First Year of the Event',
				'name' => 'events_first_year',
				'type' => 'select',
				'choices' => array (
					2018 => 2018,
					2017 => 2017,
					2016 => 2016,
					2015 => 2015,
					2014 => 2014,
					2013 => 2013,
					2012 => 2012,
					2011 => 2011,
					2010 => 2010,
					2009 => 2009,
					2008 => 2008,
					2007 => 2007,
					2006 => 2006,
					2005 => 2005,
					2004 => 2004,
					2003 => 2003,
					2002 => 2002,
					2001 => 2001,
					2000 => 2000,
					1999 => 1999,
					1998 => 1998,
					1997 => 1997,
					1996 => 1996,
					1995 => 1995,
					1994 => 1994,
					1993 => 1993,
					1992 => 1992,
					1991 => 1991,
					1990 => 1990,
					1989 => 1989,
					1988 => 1988,
					1987 => 1987,
					1986 => 1986,
					1985 => 1985,
					1984 => 1984,
					1983 => 1983,
					1982 => 1982,
					1981 => 1981,
					1980 => 1980,
					1979 => 1979,
					1978 => 1978,
					1977 => 1977,
					1976 => 1976,
					1975 => 1975,
					1974 => 1974,
					1973 => 1973,
					1972 => 1972,
					1971 => 1971,
					1970 => 1970,
					1969 => 1969,
					1968 => 1968,
					1967 => 1967,
					1966 => 1966,
					1965 => 1965,
					1964 => 1964,
					1963 => 1963,
					1962 => 1962,
					1961 => 1961,
					1960 => 1960,
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539e2b7d5752f',
				'label' => 'Number of Event Participant\'s Last Year',
				'name' => 'event_participants',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53f539e07a9d9',
				'label' => 'Event Participant Limit',
				'name' => 'event_participant_limit',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53f7db7fb5b10',
				'label' => 'Series Name',
				'name' => 'event_series',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2c6757530',
				'label' => 'Men\'s Record',
				'name' => 'mens_record',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2cd257531',
				'label' => 'Masters Men (40+) Record',
				'name' => 'masters_men_record',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2cf857532',
				'label' => 'Women\'s Record',
				'name' => 'womens_record',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2d0257533',
				'label' => 'Masters Women (40+) Record',
				'name' => 'masters_women_record',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2d2557534',
				'label' => 'Event Photo 1',
				'name' => 'event_photo_1',
				'type' => 'text',
				'instructions' => 'Enter the complete file path for the photo. (http://trailrunner.com/file.jpg)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2d9357535',
				'label' => 'Event Photo 2',
				'name' => 'event_photo_2',
				'type' => 'text',
				'instructions' => 'Enter the complete file path for the photo. (http://trailrunner.com/file.jpg)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2da457536',
				'label' => 'Event Photo 3',
				'name' => 'event_photo_3',
				'type' => 'text',
				'instructions' => 'Enter the complete file path for the photo. (http://trailrunner.com/file.jpg)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2dac57537',
				'label' => 'Starting Elevation',
				'name' => 'starting_elevation',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2deb57538',
				'label' => 'High Point',
				'name' => 'high_point',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2e1257539',
				'label' => 'Percent of the course on trails?',
				'name' => 'course_trail_percentage',
				'type' => 'select',
				'choices' => array (
					'100%' => '100%',
					'95%' => '95%',
					'90%' => '90%',
					'85%' => '85%',
					'80%' => '80%',
					'75%' => '75%',
					'70%' => '70%',
					'65%' => '65%',
					'60%' => '60%',
					'55%' => '55%',
					'50%' => '50%',
					'45%' => '45%',
					'40%' => '40%',
					'35%' => '35%',
					'30%' => '30%',
					'25%' => '25%',
					'20%' => '20%',
					'15%' => '15%',
					'10%' => '10%',
					'5%' => '5%',
					'0%' => '0%',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539e2e9b5753a',
				'label' => 'Course Map (.gpx or .kml file)',
				'name' => 'course_map',
				'type' => 'text',
				'instructions' => 'Enter the complete file path for the course map. (http://trailrunner.com/file.gpx)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e2fa36a8c7',
				'label' => 'Event Date 2018',
				'name' => 'event_date_2018',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e2fe96a8c9',
				'label' => 'Event Date 2017',
				'name' => 'event_date_2017',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e2ff16a8ca',
				'label' => 'Event Date 2016',
				'name' => 'event_date_2016',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e2ff86a8cb',
				'label' => 'Event Date 2015',
				'name' => 'event_date_2015',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e300f6a8cc',
				'label' => 'Event Date 2014',
				'name' => 'event_date_2014',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30136a8cd',
				'label' => 'Event Date 2013',
				'name' => 'event_date_2013',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30176a8ce',
				'label' => 'Event Date 2012',
				'name' => 'event_date_2012',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e301b6a8cf',
				'label' => 'Event Date 2011',
				'name' => 'event_date_2011',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30206a8d0',
				'label' => 'Event Date 2010',
				'name' => 'event_date_2010',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e303b6a8d1',
				'label' => 'Event Date 2009',
				'name' => 'event_date_2009',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30416a8d2',
				'label' => 'Event Date 2008',
				'name' => 'event_date_2008',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30456a8d3',
				'label' => 'Event Date 2007',
				'name' => 'event_date_2007',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30496a8d4',
				'label' => 'Event Date 2006',
				'name' => 'event_date_2006',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e304d6a8d5',
				'label' => 'Event Date 2005',
				'name' => 'event_date_2005',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30526a8d6',
				'label' => 'Event Date 2004',
				'name' => 'event_date_2004',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30566a8d7',
				'label' => 'Event Date 2003',
				'name' => 'event_date_2003',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30596a8d8',
				'label' => 'Event Date 2002',
				'name' => 'event_date_2002',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e305d6a8d9',
				'label' => 'Event Date 2001',
				'name' => 'event_date_2001',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30626a8da',
				'label' => 'Event Date 2000',
				'name' => 'event_date_2000',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30676a8db',
				'label' => 'Event Date 1999',
				'name' => 'event_date_1999',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e306f6a8dc',
				'label' => 'Event Date 1998',
				'name' => 'event_date_1998',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30736a8dd',
				'label' => 'Event Date 1997',
				'name' => 'event_date_1997',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e30776a8de',
				'label' => 'Event Date 1996',
				'name' => 'event_date_1996',
				'type' => 'text',
				'instructions' => 'Format date MM/DD/YYYY',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_539e307f6a8df',
				'label' => 'Event Results 2018',
				'name' => 'event_results_2018',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2018',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30d06a8e0',
				'label' => 'Event Results 2017',
				'name' => 'event_results_2017',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2017',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30d76a8e1',
				'label' => 'Event Results 2016',
				'name' => 'event_results_2016',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2016',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30dc6a8e2',
				'label' => 'Event Results 2015',
				'name' => 'event_results_2015',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2015',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30e36a8e3',
				'label' => 'Event Results 2014',
				'name' => 'event_results_2014',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2014',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30ea6a8e4',
				'label' => 'Event Results 2013',
				'name' => 'event_results_2013',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2013',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30f26a8e5',
				'label' => 'Event Results 2012',
				'name' => 'event_results_2012',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2012',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30f86a8e6',
				'label' => 'Event Results 2011',
				'name' => 'event_results_2011',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2011',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e30fd6a8e7',
				'label' => 'Event Results 2010',
				'name' => 'event_results_2010',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2010',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31026a8e8',
				'label' => 'Event Results 2009',
				'name' => 'event_results_2009',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2009',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31086a8e9',
				'label' => 'Event Results 2008',
				'name' => 'event_results_2008',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2008',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31146a8ea',
				'label' => 'Event Results 2007',
				'name' => 'event_results_2007',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2007',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31196a8eb',
				'label' => 'Event Results 2006',
				'name' => 'event_results_2006',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2006',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e311e6a8ec',
				'label' => 'Event Results 2005',
				'name' => 'event_results_2005',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2005',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31256a8ed',
				'label' => 'Event Results 2004',
				'name' => 'event_results_2004',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2004',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e312c6a8ee',
				'label' => 'Event Results 2003',
				'name' => 'event_results_2003',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2003',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31316a8ef',
				'label' => 'Event Results 2002',
				'name' => 'event_results_2002',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2002',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31366a8f0',
				'label' => 'Event Results 2001',
				'name' => 'event_results_2001',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2001',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e313e6a8f1',
				'label' => 'Event Results 2000',
				'name' => 'event_results_2000',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results2000',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31446a8f2',
				'label' => 'Event Results 1999',
				'name' => 'event_results_1999',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results1999',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e314f6a8f3',
				'label' => 'Event Results 1998',
				'name' => 'event_results_1998',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results1998',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e31576a8f4',
				'label' => 'Event Results 1997',
				'name' => 'event_results_1997',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results1997',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e315d6a8f5',
				'label' => 'Event Results 1996',
				'name' => 'event_results_1996',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://website.com/results1996',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 3,
	));
}


/*************************************************/
/************* ORDER RACE EVENTS *****************/
/*************************************************/
add_action('pre_get_posts', 'my_pre_get_posts');

function my_pre_get_posts( $query )
{
	// validate
	if( is_admin() )
	{
		return $query;
	}

	// project example
	if( isset($query->query_vars['post_type']) && $query->query_vars['post_type'] == 'event' ) {
		$query->set('orderby', 'meta_value_num');  
		$query->set('meta_key', 'event_date');  
		$query->set('order', 'ASC'); 
	}

	// always return
	return $query;
 
}


/************************************************************/
/************* RACE CALENDAR SEARCH FILTERING ***************/
/************************************************************/

function buildSelect($tax){	
	$terms = get_terms($tax);
	$x = '<select name="'. $tax .'">';
	$x .= '<option value="">Select '. ucfirst($tax) .'</option>';
	foreach ($terms as $term) {
		$x .= '<option value="' . $term->slug . '">' . $term->name . '</option>';	
	}
	$x .= '</select>';
	return $x;
}


/************* COMMENT LAYOUT *********************/

// Comment Layout
function bones_comments( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment; ?>
	<div id="comment-<?php comment_ID(); ?>" <?php comment_class('cf'); ?>>
	<article  class="cf">
		<header class="comment-author vcard">
			<?php /*
				this is the new responsive optimized comment image. It used the new HTML5 data-attribute to display comment gravatars on larger screens only. What this means is that on larger posts, mobile sites don't have a ton of requests for comment images. This makes load time incredibly fast! If you'd like to change it back, just replace it with the regular wordpress gravatar call:
				echo get_avatar($comment,$size='32',$default='<path_to_url>' );
			*/ ?>
			<?php // custom gravatar call ?>
			<?php
				// create variable
				$bgauthemail = get_comment_author_email();
			?>
			<img data-gravatar="http://www.gravatar.com/avatar/<?php echo md5( $bgauthemail ); ?>?s=40" class="load-gravatar avatar avatar-48 photo" height="40" width="40" src="<?php echo get_template_directory_uri(); ?>/library/images/nothing.gif" />
			<?php // end custom gravatar call ?>
			<?php printf(__( '<cite class="fn">%1$s</cite> %2$s', 'bonestheme' ), get_comment_author_link(), edit_comment_link(__( '(Edit)', 'bonestheme' ),'  ','') ) ?>
			<time datetime="<?php echo comment_time('Y-m-j'); ?>"><a href="<?php echo htmlspecialchars( get_comment_link( $comment->comment_ID ) ) ?>"><?php comment_time(__( 'F jS, Y', 'bonestheme' )); ?> </a></time>

		</header>
		<?php if ($comment->comment_approved == '0') : ?>
		<div class="alert alert-info">
			<p><?php _e( 'Your comment is awaiting moderation.', 'bonestheme' ) ?></p>
		</div>
		<?php endif; ?>
		<section class="comment_content cf">
			<?php comment_text() ?>
		</section>
		<?php comment_reply_link(array_merge( $args, array('depth' => $depth, 'max_depth' => $args['max_depth']))) ?>
	</article>
	<?php // </li> is added by WordPress automatically ?>
<?php
} // don't remove this bracket!


/* DON'T DELETE THIS CLOSING TAG */ ?>
